In [1]:
import pandas as pd
import glob
import xml.etree.ElementTree as ET

# Extracting

In [2]:
def extract_from_csv(file):
    df = pd.read_csv(file)
    return df

In [3]:
def extract_from_json(file):
    df = pd.read_json(file, lines=True)
    return df

In [4]:
def extract_from_xml(file):
    df = pd.DataFrame(columns=['name', 'height', 'weight'])
    tree = ET.parse(file)
    root = tree.getroot()
    for person in root:
        name = person.find("name").text
        height = float(person.find("height").text)
        weight = float(person.find("weight").text)
        new_row = pd.DataFrame({"name":[name], "height":[height], "weight":[weight]})
        df = pd.concat([df, new_row], ignore_index=True)
    return df

# Transform

In [5]:
def transform(df):
    df['height'] = round(df['height']*0.025,2)
    df['weight'] = round(df['weight']*0.45,2)
    return df

# load

In [14]:
def load(df):
    df.to_csv("FinalCSV.csv", index=False)

# Running ETL

In [7]:
df = pd.DataFrame(columns=["name", "height", "weight"])

In [8]:
for file in glob.glob("*.csv"):
    new_df = extract_from_csv(file)
    df = pd.concat([df,new_df], ignore_index=True)

C:\Users\gagan\AppData\Local\Temp\ipykernel_15060\1974560900.py:3: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df,new_df], ignore_index=True)

In [9]:
df

     name  height  weight
0   hello    5.50   45.00
1    alex   65.78  112.99
2    ajay   71.52  136.49
3   alice   69.40  153.03
4    ravi   68.22  142.34
5     joe   67.79  144.30
6    alex   65.78  112.99
7    ajay   71.52  136.49
8   alice   69.40  153.03
9    ravi   68.22  142.34
10    joe   67.79  144.30
11   alex   65.78  112.99
12   ajay   71.52  136.49
13  alice   69.40  153.03
14   ravi   68.22  142.34
15    joe   67.79  144.30

In [10]:
for file in glob.glob("*.json"):
    new_df = extract_from_json(file)
    df = pd.concat([df,new_df], ignore_index=True)

In [11]:
df

     name  height  weight
0   hello    5.50   45.00
1    alex   65.78  112.99
2    ajay   71.52  136.49
3   alice   69.40  153.03
4    ravi   68.22  142.34
5     joe   67.79  144.30
6    alex   65.78  112.99
7    ajay   71.52  136.49
8   alice   69.40  153.03
9    ravi   68.22  142.34
10    joe   67.79  144.30
11   alex   65.78  112.99
12   ajay   71.52  136.49
13  alice   69.40  153.03
14   ravi   68.22  142.34
15    joe   67.79  144.30
16   jack   68.70  123.30
17    tom   69.80  141.49
18  tracy   70.01  136.46
19   john   67.90  112.37
20   jack   68.70  123.30
21    tom   69.80  141.49
22  tracy   70.01  136.46
23   john   67.90  112.37
24   jack   68.70  123.30
25    tom   69.80  141.49
26  tracy   70.01  136.46
27   john   67.90  112.37

In [12]:
for file in glob.glob("*.xml"):
    new_df = extract_from_xml(file)
    df = pd.concat([df,new_df], ignore_index=True)

C:\Users\gagan\AppData\Local\Temp\ipykernel_15060\646709895.py:10: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, new_row], ignore_index=True)
C:\Users\gagan\AppData\Local\Temp\ipykernel_15060\646709895.py:10: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, new_row], ignore_index=True)
C:\Users\gagan\AppData\Local\Temp\ipykernel_15060\646709895.py:10: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, new_row], ignore_index=True)

In [13]:
df

     name  height  weight
0   hello    5.50   45.00
1    alex   65.78  112.99
2    ajay   71.52  136.49
3   alice   69.40  153.03
4    ravi   68.22  142.34
5     joe   67.79  144.30
6    alex   65.78  112.99
7    ajay   71.52  136.49
8   alice   69.40  153.03
9    ravi   68.22  142.34
10    joe   67.79  144.30
11   alex   65.78  112.99
12   ajay   71.52  136.49
13  alice   69.40  153.03
14   ravi   68.22  142.34
15    joe   67.79  144.30
16   jack   68.70  123.30
17    tom   69.80  141.49
18  tracy   70.01  136.46
19   john   67.90  112.37
20   jack   68.70  123.30
21    tom   69.80  141.49
22  tracy   70.01  136.46
23   john   67.90  112.37
24   jack   68.70  123.30
25    tom   69.80  141.49
26  tracy   70.01  136.46
27   john   67.90  112.37
28  simon   67.90  112.37
29  jacob   66.78  120.67
30  cindy   66.49  127.45
31   ivan   67.62  114.14
32  simon   67.90  112.37
33  jacob   66.78  120.67
34  cindy   66.49  127.45
35   ivan   67.62  114.14
36  simon   67.90  112.37
37  jacob   66.78  120.67
38  cindy   66.49  127.45
39   ivan   67.62  114.14

In [15]:
load(df)